FROM ubuntu
RUN apt-get -y update --fix-missing
RUN apt-get install tzdata
RUN apt-get install -y apache2
RUN apt-get install -y apache2-utils
RUN apt-get install -y mysql-server
RUN apt-get install -y php libapache2-mod-php
WORKDIR /var/www/html
RUN rm index.html
copy /Desktop/domainmod /var/www/html
RUN apt-get clean
Expose 80
CMD ["apache2ctl" , "-D" , "FOREGROUND"]


